sudo: required
dist: xenial

script:
  - bash -xve ./test/install_ros_kinetic.sh
  - source /opt/ros/kinetic/setup.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_prepare_dummy_files.bash
  - rostest pimouse_run_corridor wall_stop.launch

